fix: avoid partial async writes
This is
<https://rust-lang.github.io/rust-clippy/master/#unused_io_amount> but
for async code.

Turns out this is really hard to trigger since it requires you to fill
up OS TCP buffers.

In production this happens with larger throughputs. In all cases that
breaks the connection because message framing will be out-of-sync. The
broker might response with `CorruptMessage` or `MessageTooLarge` and you
will likely find one of the following errors within the broker logs:

```text
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 2021161080 larger than 104857600)
````

```text
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = -1234)
```